### ISSUE TITLE
Python Exe works fine, But c-sharp exe not working

### ISSUE THREAD

**Issue by shivbuyya** [meshtastic/c-sharp#49]
Hi,

**c-sharp:**
I have downloaded c-sharp exe version 1.0.31 [Meshtastic CLI 1.0.31](https://github.com/meshtastic/c-sharp/releases/tag/v1.0.31):
I have connected my LoRa node and when I run below command, it is not showing any output.
**>Meshtastic.Cli.exe info**

**Python:**
But, Python Exe version 1.2.93: It is working fine, when I run below command using Python executable downloaded from https://github.com/meshtastic/python/releases/download/1.2.90/meshtastic_windows. 

**>> meshtastic_windows.exe --info**

_Connected to radio

Owner: Unknown 75e0 (?E0)
My info: { "myNodeNum": 2224649696, "numBands": 8, "firmwareVersion": "1.2.13", "messageTimeoutMsec": 300000, "minAppVersion": 20200, "maxChannels": 8 }
Nodes in mesh:  {'num': 2224649696, 'user': {'id': '!849975e0', 'longName': 'Unknown 75e0', 'shortName': '?E0', 'macaddr': '78:21:84:99:75:e0', 'team': 'MAGENTA'}, 'position': {}}

Preferences: { "lsSecs": 300, "region": "EU433" }

Channels:
  PRIMARY psk=default { "modemConfig": "Bw125Cr48Sf4096", "psk": "AQ==" }

Primary channel URL: https://www.meshtastic.org/d/#CgUYAyIBAQ_

Please suggest how to resolve the issue?

**Comment by garthvh** [comment]
Meshtastic.Cli info works fine here
