### ISSUE TITLE
Update to latest System.Text.Json

### ISSUE THREAD

**Issue by parkerreno** [meshtastic/c-sharp#94]
Current version of System.Text.Json (8.0.0) has vulnerabilities.  While I am unsure whether there is an attack vector in this repo, it's best practice to update.  This package is not directly pulled in, but is a transitive dependency from the Microsoft.Extensions packages and System.CommandLine.Hosting package.

Will open a PR shortly with fixes.

Vulnerabilities:
https://github.com/advisories/GHSA-8g4q-xg66-9fp4
https://github.com/advisories/GHSA-hh2w-p6rv-4g7w

**Comment by thebentern** [comment]
> Current version of System.Text.Json (8.0.0) has vulnerabilities. While I am unsure whether there is an attack vector in this repo, it's best practice to update. This package is not directly pulled in, but is a transitive dependency from the Microsoft.Extensions packages and System.CommandLine.Hosting package.
> 
> Will open a PR shortly with fixes.
> 
> Vulnerabilities: [GHSA-8g4q-xg66-9fp4](https://github.com/advisories/GHSA-8g4q-xg66-9fp4) [GHSA-hh2w-p6rv-4g7w](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w)

I don't believe there is an attack vector, as it's a CLI / Lib, but it's possible a consumer of the package could be, so thanks for the heads up. Looking forward to the PR
